LIBS = -std=c++11
CC = g++
BIN = bin
DIR = Implementation

all: ArrayLinearList ArrayLinearListImproved ArrayStack ArrayQueue Chain CircularWithHeader LinkedStack

ArrayLinearList:
	$(CC) $(DIR)/ArrayLinearList.cpp -o $(BIN)/ArrayLinearList $(LIBS)

ArrayLinearListImproved:
	$(CC) $(DIR)/ArrayLinearListImproved.cpp -o $(BIN)/ArrayLinearListImproved $(LIBS)

ArrayStack:
	$(CC) $(DIR)/ArrayStack.cpp -o $(BIN)/ArrayStack $(LIBS)

ArrayQueue:
	$(CC) -w $(DIR)/ArrayQueue.cpp -o $(BIN)/ArrayQueue $(LIBS)

Chain:
	$(CC) $(DIR)/Chain.cpp -o $(BIN)/Chain $(LIBS)

CircularWithHeader:
	$(CC) $(DIR)/CircularWithHeader.cpp -o $(BIN)/CircularWithHeader $(LIBS)

LinkedStack:
	$(CC) $(DIR)/LinkedStack.cpp -o $(BIN)/LinkedStack $(LIBS)
