CC = javac
EXE = java
BIN = bin
DIR = dataStructures
CLEAR = clear && clear &&

all: Graph

Graph:
	$(CLEAR) $(CC) -d $(BIN) $(DIR)/Graph.java $(DIR)/AdjacencyList.java

runGraph:
	$(CLEAR) $(EXE) -cp $(BIN) $(DIR).AdjacencyList
